### ISSUE TITLE
notebookまとめ

### ISSUE THREAD

**Issue by yanoyoshiki** [yanoyoshiki/torch_tutorial_y-i-2#3]
**現在ntoebookが中村と全く違う形式になってしまっている**
--
矢野がとりあえず実行可能なノートブックにしたため、非常に見づらい形式になっっている

**問題点を洗い出し、追記可能な説明を加えてほしい**
--
自分が作成したnotebookに近づけるように

**実行のストーリーがわかるように追記**
--
それぞれの構成要素を詳しく説明する必要なし。分析の枠組みやその前置きの追記

**Additional context**
--
対象ファイルは以下の2つです。
1. Optuna_with_PyTorch_CIFAR10.ipynb
2. Optuna_with_PyTorch_MNIST.ipynb

別ブランチにて作業を行なってください。内容を確認後後でマージしておきます。
何かわからないことがあればすぐ聞いてください。

**Comment by Issa-N** [comment]
今、実行しています。
